version: '3'

services:

  web:
    build: .
    ports:
      - "4567:4567"
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    command: bundle exec ruby oai_solr.rb -o 0.0.0.0

volumes:
  gem_cache:
